# Generated by Django 5.2.7 on 2025-10-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='000000', max_length=255),
            preserve_default=False,
        ),
    ]
